name: Find tabs

on: [push]

jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get updated files
        run: |
          git log
          git diff HEAD HEAD~1 --name-only
  
  check_files:
    needs: get_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: [file1.txt, file2.txt, file3.txt]
    steps:
      - name: check files
        uses: actions/checkout@v3
      - run: |
          ls -la
          grep -n $'\t' ${{ matrix.files }} >> ${{ matrix.files }}.log 2>&1
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.files }}.log