name: Find tabs

on: [push]

jobs:
  get_updated_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get updated files
        id: files
        run: |
          file_list=`git diff HEAD HEAD~1 --name-only | grep -v "workflow"`
          echo $file_list
          if [ -z "file_list" ]
          then
            echo "Changed files not found"
          else
            sudo apt-get install jq
            json_file_list=$(git diff HEAD HEAD~13 --name-only | grep -v "workflow" | jq -R -s -c 'split("\n")[:-1]')
            echo $json_file_list
            echo "::set-output name=files::$json_file_list"
          fi
    outputs:
      files: ${{ steps.files.outputs.files }}

  check_files:
    needs: get_updated_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJson(needs.get_updated_files.outputs.files) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check file
        run: |
          echo ${{ matrix.files }}
          # ls -la
          # grep -n $'\t' ${{ matrix.files }}
          # grep -n $'\t' ${{ matrix.files }} >> ${{ matrix.files }}.log 2>&1
      # - name: upload logs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ${{ matrix.files }}.log