name: Find tabs

on: [push]

jobs:
  get_files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get updated files
        id: files
        run: |
          #git log
          files=$(git diff HEAD HEAD~1 --name-only)
          echo "::set-output name=files::$files"
  
  check_files:
    needs: get_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ steps.files.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check file
        run: |
          ls -la
          grep -n $'\t' ${{ matrix.files }}
          grep -n $'\t' ${{ matrix.files }} >> ${{ matrix.files }}.log 2>&1
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.files }}.log