name: Find tabs

on: [push]

jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - name: get-files
        uses: actions/checkout@v3
          fetch-depth: 0
        run: git log

#   check_files:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         files: ${{ get-files.output.files }}
#     steps:
#       - name: check files
#         uses: actions/checkout@v2
#       - run: grep -n $'\t' ${{ get-files.output.files }} >> ${{ get-files.output.files }}.log 2>&1
#       - name: upload logs
#         uses: actions/upload-artifact@v2
#         with:
#           path: ${{ get-files.output.files }}.log
