name: Find tabs

on: [push]

jobs:
  get_files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.matrix }}
    steps:
      - uses: action/checkout@v2
      - id: get-files
      run: |
        matrix=$(git diff HEAD HEAD~1 --name-only)
        echo $matrix
  
  check_files:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ steps.get-files.matrix }}
    steps:
      - name: check files
      - run: grep -n $'\t' ${{ steps.get-files.matrix }} >> ${{ steps.get-files }}.log 2>&1
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.get-files.matrix }}.log