name: Find tabs

on: [pull_request]

jobs:
  get_updated_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get updated files
        id: files
        run: |
          json_file_list=$(git diff HEAD HEAD~1 --name-only --diff-filter=M | jq -R -s -c 'split("\n")[:-1]')
          echo $json_file_list
          echo "::set-output name=files::$json_file_list"
    outputs:
      files: ${{ steps.files.outputs.files }}

  check_files:
    needs: get_updated_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJson(needs.get_updated_files.outputs.files) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check file
        run: |
          echo ${{ matrix.files }}
          if [ -z grep -n $'\t' ${{ matrix.files }} ]
          then
            echo "Tabs not found" >> ${{ matrix.files }}.log
          else
            grep -n $'\t' ${{ matrix.files }}
            grep -n $'\t' ${{ matrix.files }} >> ${{ matrix.files }}.log
          fi
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.files }}.log